add updateBucketById api
Storj/storj.js pull request #78
Opened 2017-04-06 20:27 UTC by nginnever

This adds an interface to make an update bucket api call to the bridge as request by https://github.com/Storj/storj.js/issues/77

2017-04-06 20:33 UTC, nginnever commented
@retrohacker seems like `getFile` is failing with bad gateway in the tests. Is this a bridge issue you may know of?

2017-04-08 03:19 UTC, retrohacker requested changes

2017-04-08 03:19 UTC, retrohacker commented on examples/upload/upload.html
> +      var rs = {on: function(){}}
I've been seeing code bases use `Function.prototype` for `noop` to keep code coverage at 100%

Thoughts on this pattern? Fine the way it is too.

2017-04-08 03:19 UTC, retrohacker commented on test/all/index.js
> +test('updateBucket', function(t) {
This shadows the `makePublic` test. Line 220 tests `makePublic` worked by downloading the file using an unauthenticated client. `makePublic` could be broken and this test would 'fix' the remote state by adding `PULL` back to the permissions before we validated we could download the file.

I'm not sure how much we can update on a bucket, but could we change something other than permissions?

Also, we need to not only use `updateBucketById`, but we also need to use `getBucket` after to verify subsequent calls reflect that state.

2017-04-08 03:19 UTC, retrohacker commented on README.md
> +### `storj.updateBucketById(bucketId, updateInfo, function cb(e) {})`
This is nit-picky, but can we change the method to `updateBucket`? We have a pattern going that is `[verb][noun]()` and this breaks that.

Later on we can overload this method to accept names, ids, etc. and derive the type from the form of the first argument.

2017-04-08 03:25 UTC, retrohacker commented
Many of these tests build on one another (the current test will make assertions about the state previous tests setup). This is probably a shortcoming in the test suite but seems like the simplicity the pattern affords outweighs the negatives. Happy to be convinced otherwise though :-)

2017-04-08 03:25 UTC, retrohacker commented
Taking a look at the tests now

2017-04-08 03:40 UTC, retrohacker commented
Its specifically failing on `createToken` and _only_ on an unauthenticated client. Super strange. @phutchins have you seen this?

![snapshot1](https://cloud.githubusercontent.com/assets/1081565/24825377/986721a8-1beb-11e7-9d78-c973430f96ce.png)

2017-04-08 03:43 UTC, retrohacker commented
It's doing a `POST` to `/buckets/[id]/tokens`

2017-04-08 06:24 UTC, nginnever commented on examples/upload/upload.html
> +      var rs = {on: function(){}}
Ah yeah that would be better but this was just a hack, I have a PR to update and clean up examples that will remove this when this is merged.

2017-04-08 06:27 UTC, nginnever commented on test/all/index.js
> +test('updateBucket', function(t) {
Ahh I was afraid of that. We have these options to test updating.

pubkeys - Array
encryptionKey - String
publicPermissions - Array

So i'll just changing this to update a pubkey.

2017-04-08 06:28 UTC, nginnever commented on README.md
> +### `storj.updateBucketById(bucketId, updateInfo, function cb(e) {})`
I am not apposed to that all and like it better myself. The name currently follows the function name used in bridge-client

2017-04-10 19:32 UTC, retrohacker approved these changes

2018-10-30 12:27 UTC, RichardLitt commented
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

2018-10-30 12:27 UTC, closed without merging